# Dynamic change numbers, config version 0.60
# This is main config for Calulate damage on tools and wapons
#
# You put in your rank name and a number as some standard, it will
# divide your number with how much damage the tool has lost.
# You can for now only change the order and use <+,/,*,->,
# will look on fix for this.
#
# Use the placeholder like this, it need to output same name has you
# set up in the config
# %number_numbervalue,tool:{a placeholder from your ranking plugin}%
#
# If you want to have two decimals use
# %number_numbervalue,decimal,tool:{a placeholder from your ranking plugin}%
#
# For calcuate armor values use placeholder below.
# %number_numbervalue,armor:{a placeholder from your ranking plugin}%
#
# If you want to have two decimals use this placeholder
# %number_numbervalue,decimal,armor:{a placeholder from your ranking plugin}%
#
# Do like this:
# Do like this:
# Values:
#   Rank:
#     Examplerank: 5


EmptyPlaceholder: false
Values:
  Rank:
    Examplerank: 6
    Examplerank1: 4
    Examplerank2: 2
  Armor:
    GOLDEN_HELMET: 1.75
    IRON_HELMET: 1.5
    DIAMOND_HELMET: 2
    NETHERITE_HELMET: 3
    GOLDEN_CHESTPLATE: 1.8
    IRON_CHESTPLATE: 1.5
    DIAMOND_CHESTPLATE: 2.5
    NETHERITE_CHESTPLATE: 3.5
    GOLDEN_LEGGINGS: 1.75
    IRON_LEGGINGS: 1.6
    DIAMOND_LEGGINGS: 2
    NETHERITE_LEGGINGS: 3.2
    GOLDEN_BOOT: 1.75
    IRON_BOOT: 1.75
    DIAMOND_BOOT: 2
    NETHERITE_BOOT: 3
  Tools:
    WOODEN_HOE: 0
    STONE_HOE: 1.5
    GOLDEN_HOE: 1.2
    IRON_HOE: 1.5
    DIAMOND_HOE: 1.7
    NETHERITE_HOE: 1.8
    WOODEN_SHOVEL: 0
    STONE_SHOVEL: 1.5
    GOLDEN_SHOVEL: 1.2
    IRON_SHOVEL: 1.5
    DIAMOND_SHOVEL: 1.8
    NETHERITE_SHOVEL: 2
    WOODEN_PICKAXE: 0
    STONE_PICKAXE: 1.5
    GOLDEN_PICKAXE: 1.2
    IRON_PICKAXE: 1.5
    DIAMOND_PICKAXE: 1.8
    NETHERITE_PICKAXE: 2.1
  Wapons:
    WOODEN_AXE: 0
    STONE_AXE: 1.2
    GOLDEN_AXE: 0.8
    IRON_AXE: 1.5
    DIAMOND_AXE: 1.8
    NETHERITE_AXE: 2
    WOODEN_SWORD: 0
    STONE_SWORD: 1.2
    GOLDEN_SWORD: 0.8
    IRON_SWORD: 1.5
    DIAMOND_SWORD: 1.8
    NETHERITE_SWORD: 2
    BOW: 1.3
    CROSSBOW: 1.3
# Math only works for tools if you change this,
# will look on better solution or remove this.
Math: {toolDurability} / {valueNumber}

